INSERT INTO departamentos (piso, nombre_departamento) VALUES
(7, 'Radio Municipal'),
(6, 'Auditoria Interna'),
(6, 'Presupuesto'),
(6, 'Tesoreria'),
(6, 'Bienes'),
(6, 'Catastro Direccion'),
(6, 'Catastro Juridico'),
(6, 'Catastro Economico'),
(6, 'Catastro Atencion'),
(6, 'Catastro Fisico'),
(5, 'Sala Politica'),
(5, 'Sindicato Empleados'),
(5, 'Gestion Social'),
(5, 'Rh Direccion'),
(5, 'Rh Fondo de Proteccion'),
(5, 'Rh Administracion'),
(5, 'Rh Nomina'),
(5, 'Rh Juridico'),
(5, 'Rh Seguridad Laboral'),
(5, 'Rh Biometrico'),
(4, 'Ingenieria Municipal'),
(4, 'Construgirardot'),
(4, 'Ingenieria Ambientes'),
(3, 'Tecnologia y Sistemas'),
(3, 'Satrim'),
(2, 'Despacho'),
(2, 'Sindicatura'),
(2, 'Relaciones Publicas'),
(2, 'Prensa'),
('PB', 'Atencion Ciudadana'),
('PB', 'Administracion'),
('Sotano', 'Compra'),
('Sotano', 'Catastro Archivo'),
('Sotano', 'Servicios Generales');